### PR TITLE
Add contents to main tag

### PR DESCRIPTION
**Pull request by Abiodun-Shittu**

### CODE REVIEW

**Review by IyiKuyoro — CHANGES_REQUESTED** [review]
You did not need to include the header in this feature. The header has nothing to do with this feature.

**Comment by IyiKuyoro** [comment]
I was also expecting to see the CSS.

**Comment by Abiodun-Shittu** [comment]
> I was also expecting to see the CSS.

I'll add it soon, thought we had to go through the HTML before CSS

**Comment by IyiKuyoro** [comment]
Close this PR.

**Pull request closed without merging**
